clc;
clear;
%%
load("..\saved_data\dataset_cleaned.mat")
load('..\saved_data\model.mat');
%%
[dataset_cleaned, val_set] = splitEachLabel(dataset_cleaned, 0.8,'randomized');
dsTrain = transform(dataset_cleaned,@preprocessing, ...
    IncludeInfo=true);
aug_val_set = transform(val_set,@preprocessing, ...
    IncludeInfo=true);
%% configurazione fine-tuning
options = trainingOptions('adam',...
    'MiniBatchSize',16,...
    'MaxEpochs',16,...
    'InitialLearnRate',1e-4,...
    'Shuffle','every-epoch',...
    'ValidationData',aug_val_set,...
    'ValidationFrequency',1024,...
    'Verbose',1,...
    'Plots','training-progress', ...
    'OutputNetwork','best-validation-loss' ...
     );
%%
fine_tuned_model = trainNetwork(dsTrain,classification_model.layerGraph,options);
